### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by reccmost** [hackxpeng/hackp5g9#4]
根据大哥的方法，我也逆出了unlock key的算法，我也想为我的小鹏做一点贡献。单兵作战，想寻求个群。
证明：0x17890

**Comment by YIFAN0831** [comment]
搞个群讨论一下啊，新版本貌似都不行了

**Comment by dodhunzhu** [comment]
有进度了喊一下~我是小白~帮你们加油~

**Comment by jdjingdian** [comment]
从P5提取的，用dex2jar反编译devtools可以看到，打开adb很简单
```
import android.debug.AdbManager;

AdbManager adbManager = (AdbManager)mContext.getSystemService("adb");
adbManager.setDebugStatus(true);
```


P7 2.12提取的devtools里，打开的地方做了判断，读systemProperty里的ro.xpeng.devcode.ver，版本是2就用isUnlockKeyValidV2。如果能改ro.xpeng.devcode.ver成1，也能继续用，但是这玩意是只读的

**Comment by YIFAN0831** [comment]
大佬，新的版本有啥办法不@jdjingdian ，这辈子最后悔的就是这次G9测试了，测试版已经用不了了

**Comment by jdjingdian** [comment]
> 大佬，新的版本有啥办法不@jdjingdian ，这辈子最后悔的就是这次G9测试了，测试版已经用不了了

等姓何的良心发现就有可能吧

**Comment by YIFAN0831** [comment]
@jdjingdian 过了这村就没有这个店么。。。

**Comment by reccmost** [comment]
> 从P5提取的，用dex2jar反编译devtools可以看到，打开adb很简单
> 
> ```
> import android.debug.AdbManager;
> 
> AdbManager adbManager = (AdbManager)mContext.getSystemService("adb");
> adbManager.setDebugStatus(true);
> ```
> 
> P7 2.12提取的devtools里，打开的地方做了判断，读systemProperty里的ro.xpeng.devcode.ver，版本是2就用isUnlockKeyValidV2。如果能改ro.xpeng.devcode.ver成1，也能继续用，但是这玩意是只读的

看到了，但是这个代码需要app执行才行，另外可否提供一些P7 2.12版的so文件？

如方便提供，可发送到：bigifo8316@docwl.com（匿名邮件，有效期到2023/09/10 12:00）

**Comment by jdjingdian** [comment]
@reccmost 麻烦查收

**Comment by jk50505k** [comment]
拉个群  俺也是搞逆向的

**Comment by qq690712575** [comment]
半桶水的安卓程序员前来支援

**Comment by huzai9527** [comment]
您好，我是网络安全专业的学生，如您方便，可否提p5,p7的相关so文件，想尝试分析一下，如果可以的话，可以发送到callmehuzai@gmail.com

**Comment by TY1991** [comment]
小鹏车主前来围观，p7升级成了可恶的2.12了，默哀

**Comment by qq690712575** [comment]
要我怎么操作

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: huzai9527 ***@***.***>
发送时间: Friday, September 15, 2023 11:50:24 AM
收件人: hackxpeng/hackp5g9 ***@***.***>
抄送: Jianle Chen ***@***.***>; Comment ***@***.***>
主题: Re: [hackxpeng/hackp5g9] 感谢 (Issue #4)


***@***.******@***.***>

―

**Comment by lianchua** [comment]
求一个群
